version: '3.3'

services:
  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_DB=tienda
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ANDres1988
    ports:
      - 5432:5432

    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ajaramillomont@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pucoDev2025
    ports:
      - 5050:80
    networks:
      - app_network

  nodejs:
    build:
      context:
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - postgresql

  networks:
    app_network:
      driver: bridge
