version: '3.3'

services:
  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_DB=tienda
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ANDres1988
    ports:
      - 5432:5432

    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ajaramillomont@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pucoDev2025
    ports:
      - 5050:80
    networks:
      - app_network

  nodejs:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - postgresql

  mysql:
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=tienda
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=ANDres1988
      - MYSQL_PORT=3306
    ports:
    - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=ANDres1988
      - PMA_HOST=mysql
    ports:
      - 8080:80
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
