version: '3.3'

services:
  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_DB=tienda
      - POSTGRES-USER=postgres
      - POSTGRES_PASSWORD=ANDres1988
    ports:
      - 5432:5432

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ajaramillomont@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pucoDev2025
    ports:
      - 5050:80
